### ISSUE TITLE
What does this repo do?

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/gsibclim#9]
Hi! @danholdaway, @rtodling 
Few questions:

1. What is the purpose of this repo? (empty readme!)
2. I didn't want to dig around, but is a test case I can build?
3. ⤴️ (Question is related to _this_ one) I would like to contribute/add clim `skin SST` generation to this repo. Any preferences/pointers as to where that should go?

**Comment by danholdaway** [comment]
@sanAkel this repo is to isolate the GSI hybrid background error model code so that it can be called from JEDI. There is a test in there but the data required to run the test isn't included with the repo as there remains some question over how to include the data. Have you spoken with Ricardo about adding sst? My understanding was that all aspects of the GSI background code would automatically port to this version.

**Comment by sanAkel** [comment]
Thanks @danholdaway 

> There is a test in there but the data required to run the test isn't included with the repo as there remains some question over how to include the data. 

I will check with @rtodling on how to get that _test_ data, we haven't been able to connect in a while (could not find a good time that works for both).

> Have you spoken with Ricardo about adding sst? My understanding was that all aspects of the GSI background code would automatically port to this version.

Do you happen to have a test case on `discover`?

**Comment by danholdaway** [comment]
There's a test that runs through saber, which is what I've been running. But things are quite in flux at the moment and it usually required specific branches. Probably best to connect with Ricardo before running something. Or hold off for a couple of weeks. We are working on incorporating the code into the standard JEDI/Saber tests and one that happens there will be something stable to work with.

**Comment by sanAkel** [comment]
Okay, will hold off for sometime and meanwhile try to reach out to Ricardo.
